<a href="https://colab.research.google.com/github/ShreeKeshavan/Machine_Learning/blob/main/Natural_Language_Processing(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk

In [2]:
#to import all nltk modules
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

## **Tokenisation**

In [3]:
from nltk.tokenize import word_tokenize
word_tokenize('I like to study data science')

['I', 'like', 'to', 'study', 'data', 'science']

In [4]:
from nltk.tokenize import sent_tokenize
sent_tokenize('I am studying data science. what are you studying? Data Science is intresting!')

['I am studying data science.',
 'what are you studying?',
 'Data Science is intresting!']

In [5]:
from nltk.tokenize import regexp_tokenize
regexp_tokenize('I-am-studying-data-science','\w+') #tokenizing the alphabets alone using regular expresssion

['I', 'am', 'studying', 'data', 'science']

## **Stemming**

In [6]:
from nltk.stem import PorterStemmer
porter = PorterStemmer()
word_list = ['friend','friends','friendship','friendships']
for word in word_list:
  print(porter.stem(word))

friend
friend
friendship
friendship


In [7]:
word_list = ['care','caring','careful']
for word in word_list:
  print(porter.stem(word))

care
care
care


In [8]:
word_list = ['organize','organizes','organizing'] #lmitations of stemmer it wont get what actually we want
for word in word_list:
  print(porter.stem(word))

organ
organ
organ


In [9]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
word_list = ['rocks','corpora','better'] #lmitations of stemmer it wont get what actually we want
for word in word_list:
  print(porter.stem(word))

rock
corpora
better


Lemmatizer

In [10]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
word_list = ['rocks','corpora','better']
for word in word_list:
  print(lemmatizer.lemmatize(word))

rock
corpus
better


In [11]:
word_list = ['good','better','best']
for word in word_list:
  print(lemmatizer.lemmatize(word, pos='a')) # pos is part of speech

good
good
best


In [12]:
word_list = ['organize','organizes','organizing']
for word in word_list:
  print(lemmatizer.lemmatize(word, pos='v')) # pos is part of speech

organize
organize
organize


pos tagging

In [13]:
from nltk import pos_tag
text = 'we are learning data science and it is interesting'
words_list = word_tokenize(text)

In [14]:
pos_tag(words_list) #part of speech of all words

[('we', 'PRP'),
 ('are', 'VBP'),
 ('learning', 'VBG'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('and', 'CC'),
 ('it', 'PRP'),
 ('is', 'VBZ'),
 ('interesting', 'VBG')]

stop words

In [15]:
from nltk.corpus import stopwords

In [16]:
sw = stopwords.words('english')

In [17]:
sw #predefined stop words in nltk

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [18]:
#tokenizing
text = 'This is an example sentence. We are learning Natural language processing using python.'
all_words = word_tokenize(text)

all_words

['This',
 'is',
 'an',
 'example',
 'sentence',
 '.',
 'We',
 'are',
 'learning',
 'Natural',
 'language',
 'processing',
 'using',
 'python',
 '.']

In [19]:
#removing stop words
words_without_sw = [w for w in all_words if w.lower() not in sw]

words_without_sw

['example',
 'sentence',
 '.',
 'learning',
 'Natural',
 'language',
 'processing',
 'using',
 'python',
 '.']

In [20]:
#manual cleaning/preprocessing
words_final = [w for w in words_without_sw if w.isalpha()]

words_final

['example',
 'sentence',
 'learning',
 'Natural',
 'language',
 'processing',
 'using',
 'python']

# **vectorizers**

### **Count Vectorizers**

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

text_documents = ['Modern humans arrived on the Indian subcontinent from Africa no later than 55000 years ago',
                  'Their long occupation, initially in varying forms of isolation as hunter-gatherers, has made the region highly diverse.',
                  'Its evidence today is found in the hymns of the Rigveda, preserved by a resolutely vigilant oral tradition, the Rigveda records the dawning of Hinduism in India.',
                  'The Dravidian languages of India were supplanted in the northern and western regions.']

c_vec = CountVectorizer()

X_c = c_vec.fit_transform(text_documents)


In [22]:
X_c.shape

(4, 57)

In [23]:
X_c #this is a sparse matrix - more elements are 0

<4x57 sparse matrix of type '<class 'numpy.int64'>'
	with 65 stored elements in Compressed Sparse Row format>

In [24]:
print(X_c) #sparse matrix representation 

  (0, 32)	1
  (0, 18)	1
  (0, 4)	1
  (0, 37)	1
  (0, 48)	1
  (0, 23)	1
  (0, 45)	1
  (0, 13)	1
  (0, 1)	1
  (0, 33)	1
  (0, 29)	1
  (0, 47)	1
  (0, 0)	1
  (0, 56)	1
  (0, 2)	1
  (1, 48)	1
  (1, 49)	1
  (1, 30)	1
  (1, 35)	1
  (1, 24)	1
  (1, 21)	1
  (1, 52)	1
  (1, 11)	1
  (1, 36)	1
  (1, 26)	1
  :	:
  (2, 12)	1
  (2, 20)	1
  (2, 44)	2
  (2, 39)	1
  (2, 6)	1
  (2, 43)	1
  (2, 53)	1
  (2, 38)	1
  (2, 51)	1
  (2, 40)	1
  (2, 7)	1
  (2, 17)	1
  (2, 22)	1
  (3, 48)	2
  (3, 21)	1
  (3, 36)	1
  (3, 22)	1
  (3, 9)	1
  (3, 28)	1
  (3, 54)	1
  (3, 46)	1
  (3, 34)	1
  (3, 3)	1
  (3, 55)	1
  (3, 42)	1


In [25]:
X_c.toarray() #array view of vector

array([[1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 1, 0, 0, 1,
        2, 0, 0, 0, 4, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0]])

In [26]:
c_vec.vocabulary_ #to show the vocabularies in the vector space

{'modern': 32,
 'humans': 18,
 'arrived': 4,
 'on': 37,
 'the': 48,
 'indian': 23,
 'subcontinent': 45,
 'from': 13,
 'africa': 1,
 'no': 33,
 'later': 29,
 'than': 47,
 '55000': 0,
 'years': 56,
 'ago': 2,
 'their': 49,
 'long': 30,
 'occupation': 35,
 'initially': 24,
 'in': 21,
 'varying': 52,
 'forms': 11,
 'of': 36,
 'isolation': 26,
 'as': 5,
 'hunter': 19,
 'gatherers': 14,
 'has': 15,
 'made': 31,
 'region': 41,
 'highly': 16,
 'diverse': 8,
 'its': 27,
 'evidence': 10,
 'today': 50,
 'is': 25,
 'found': 12,
 'hymns': 20,
 'rigveda': 44,
 'preserved': 39,
 'by': 6,
 'resolutely': 43,
 'vigilant': 53,
 'oral': 38,
 'tradition': 51,
 'records': 40,
 'dawning': 7,
 'hinduism': 17,
 'india': 22,
 'dravidian': 9,
 'languages': 28,
 'were': 54,
 'supplanted': 46,
 'northern': 34,
 'and': 3,
 'western': 55,
 'regions': 42}

Hashing Vectorizer

In [27]:
from sklearn.feature_extraction.text import HashingVectorizer
h_vec = HashingVectorizer(n_features= 20)
h_vec.fit_transform(text_documents)
X_h =h_vec.fit_transform(text_documents)

In [28]:
X_h.shape #matrix of the data

(4, 20)

In [29]:
X_h.toarray() #to execute in array

array([[ 0.        , -0.30151134,  0.30151134,  0.        ,  0.        ,
         0.        ,  0.60302269,  0.        , -0.30151134,  0.        ,
         0.        , -0.30151134, -0.30151134,  0.        ,  0.        ,
         0.        ,  0.        ,  0.30151134, -0.30151134,  0.        ],
       [ 0.        , -0.25      ,  0.25      ,  0.        , -0.25      ,
         0.25      ,  0.        ,  0.        ,  0.        ,  0.25      ,
         0.        ,  0.        ,  0.        , -0.25      ,  0.        ,
         0.25      ,  0.5       ,  0.        , -0.25      ,  0.5       ],
       [ 0.        , -0.13608276,  0.        ,  0.        ,  0.        ,
        -0.13608276, -0.27216553,  0.13608276,  0.        ,  0.27216553,
        -0.13608276,  0.        ,  0.40824829, -0.13608276,  0.        ,
         0.13608276,  0.27216553,  0.13608276, -0.68041382,  0.13608276],
       [ 0.        ,  0.        ,  0.        , -0.45883147, -0.22941573,
        -0.45883147,  0.22941573,  0.        ,  

**Tfidf Vectorizer**

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
docs = ['The sky is blue','The sun is bright','The water is blue']

In [34]:
t_vec = TfidfVectorizer()
X_t = t_vec.fit_transform(docs)
X_t.toarray()

array([[0.50410689, 0.        , 0.39148397, 0.66283998, 0.        ,
        0.39148397, 0.        ],
       [0.        , 0.6088451 , 0.35959372, 0.        , 0.6088451 ,
        0.35959372, 0.        ],
       [0.50410689, 0.        , 0.39148397, 0.        , 0.        ,
        0.39148397, 0.66283998]])

DIFFERENCE BETWEEN VECTORIZERS

In [35]:
docs = ['The sky is blue','The sun is bright','The water is blue']

In [36]:
c_vec = CountVectorizer()
h_vec = HashingVectorizer()
t_vec = TfidfVectorizer()

In [42]:
X_c = c_vec.fit_transform(docs)
X_h = h_vec.fit_transform(docs) # we cant able to view vocabularies in hashing vectorizer 
X_t = t_vec.fit_transform(docs)

In [43]:
c_vec.get_feature_names_out() #to view vocabularies of count vectorizer

array(['blue', 'bright', 'is', 'sky', 'sun', 'the', 'water'], dtype=object)

In [44]:
t_vec.get_feature_names_out() #to view vocabularies of tfidf vectorizer

array(['blue', 'bright', 'is', 'sky', 'sun', 'the', 'water'], dtype=object)

Sentimental Analysis

method 1

In [1]:
!pip install vaderSentiment

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.6 MB/s eta 0:00:00


In [3]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyszer = SentimentIntensityAnalyzer()
vs = analyszer.polarity_scores('The food was great')
vs

# neg - negative, neu - neutral, pos - positive

{'neg': 0.0, 'neu': 0.423, 'pos': 0.577, 'compound': 0.6249}

method 2

In [4]:
!pip install flair

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 373.1/373.1 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 17.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 57.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.5/788.5 kB 42.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 54.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [18]:
from flair.models import TextClassifier
from flair.data import Sentence

In [21]:
Classifier = TextClassifier.load('en-sentiment')
sentence = Sentence("The food was very bad!")
Classifier.predict(sentence)

In [22]:
sentence.labels

['Sentence[6]: "The food was very bad!"'/'NEGATIVE' (0.9999)]